name = "hom-key-register-v2"

compatibility_date = "2025-09-13"

[[services]]
binding = "WORKER_BINDING"
service = "hom-key-register-v2" # Or "hom-key-register-v2", depending on your deployed name

[assets]
directory = "./"
