name = "hom-key-register"

compatibility_date = "2025-09-13"

[[services]]
binding = "WORKER_BINDING"
service = "hom-key-register"

# This section is for a Pages project with a static output
[pages_build_output]
dir = "./"
