name = "hom-key-register" # Or whatever your Pages project name is

compatibility_date = "2025-09-07"

# This section creates the service binding to your Worker
[[services]]
binding = "MY_WORKER"
service = "hom-key-register"

# This section is for a Pages project with a static output
[pages_build_output]
dir = "./"
