name = "hom-key-register"

compatibility_date = "2025-09-13"

[[services]]
binding = "WORKER_BINDING"
service = "hom-key-register"

# This section is for a Pages project with a static output
# [pages_build_output]
# dir = "./"

[[d1_databases]]
binding = "DB"
database_name = "key-register-db"
database_id = "77815214-8fc2-4142-8394-2af427139531"
